substitutions:
  static_ip: 10.10.0.106
  friendly_name: "Albert"

esphome:
  name: albert-room
  platform: ESP8266
  board: nodemcuv2

<<: !include common/base.yaml
<<: !include common/log_8266.yaml
<<: !include common/main.yaml

i2c:
  sda: D2
  scl: D1
  scan: false

display:
  - platform: lcd_pcf8574
    id: main_display
    dimensions: 16x2
    address: 0x27
    lambda: |-
      it.strftime(0, 0, "%d.%m.%Y %H:%M", id(current_time).now());
      it.printf(0, 1, "Temp.: %.1f*C", id(temperature).state);

time:
- platform: sntp
  id: current_time

dallas:
  - pin: D5

sensor:
  - platform: dallas
    index: 0
    id: "temperature"
    name: "${friendly_name} - Temperatura"

  - platform: wifi_signal
    name: "${friendly_name} - WiFi"
    update_interval: 60s

  - platform: adc
    pin: A0
    name: "${friendly_name} - Moc podświetlenia"
    update_interval: 250ms
    internal: true
    filters:
      - lambda: |-
          float MAX_DIFFERENCE = 0.05;
          static float last_value = NAN;
          if (isnan(last_value) || std::abs(x - last_value) > MAX_DIFFERENCE)
            return last_value = x;
          else
            return {};
    on_value:
      then:
        - light.turn_on:
            id: backlight_led
            transition_length: 0ms
            brightness: !lambda 'return x;'

output:
  - platform: esp8266_pwm
    pin: D7
    frequency: 1000 Hz
    id: pwm_output

light:
  - platform: monochromatic
    id: backlight_led
    output: pwm_output
    name: "${friendly_name} - Podświetlenie"
