substitutions:
  static_ip: 10.10.0.121
  friendly_name: "Lampa na belce"

esphome:
  name: beam-lamp
  platform: ESP32
  board: esp32doit-devkit-v1

<<: !include common/base.yaml
<<: !include common/log_32.yaml
<<: !include common/main.yaml

sensor:
  - platform: uptime
    name: "${friendly_name} - Czas pracy"
    id: uptime_sensor
    update_interval: 60s

  - platform: wifi_signal
    name: "${friendly_name} - WiFi"
    update_interval: 60s

light:
  - platform: monochromatic
    name: "${friendly_name} - LED"
    output: led_output
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 500ms

output:
  - platform: ledc
    id: led_output
    pin: GPIO25
    frequency: 19531Hz
