substitutions:
  static_ip: 10.10.0.116
  friendly_name: "Mini"

esphome:
  name: mini3
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  #board: nodemcuv2
  #board: d1_mini
  #board: esp01
  #platform: ESP32
  #board: esp32doit-devkit-v1

<<: !include common/base.yaml
<<: !include common/log_8266.yaml
