substitutions:
  static_ip: 10.10.0.122
  friendly_name: "Pilot"

esphome:
  name: remote
  platform: ESP32
  board: lolin32_lite

  on_shutdown:
    then:
      lambda: |-
        id(main_display).turn_off();

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light
  fast_connect: true
  output_power: 12dB

  manual_ip:
    static_ip: "${static_ip}"
    gateway: 10.10.0.10
    subnet: 255.255.255.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8

ota:
  password: !secret ota_password

<<: !include common/log_32.yaml

deep_sleep:
  id: main_deep_sleep
  run_duration:
    default: 3s
    gpio_wakeup_reason: 30s
  sleep_duration: 15min
  wakeup_pin:
    number: GPIO12
  wakeup_pin_mode: INVERT_WAKEUP
#  esp32_ext1_wakeup:
#    mode: ALL_LOW
#    pins:
#      - GPIO27
#      - GPIO14

mqtt:
  id: mqtt_client
  broker: 10.10.0.103
  discovery: true
  topic_prefix: remote
  birth_message:
    topic: remote/availability
    payload: ""
  will_message:
    topic: remote/availability
    payload: ""

i2c:
  sda: GPIO23
  scl: GPIO19
  scan: false

script:
  - id: menu_action
    then:
      - lambda: |-
          auto active_page = id(main_display).get_active_page();
          if (active_page == id(page_play_rmf24))
            id(mqtt_client).publish("hass/script/rmf24", "");
          if (active_page == id(page_play_radio357))
            id(mqtt_client).publish("hass/script/radio357", "");
          if (active_page == id(page_play_antyradio))
            id(mqtt_client).publish("hass/script/antyradio", "");
          if (active_page == id(page_play_nowyswiat))
            id(mqtt_client).publish("hass/script/nowyswiat", "");
          if (active_page == id(page_play_tokfm))
            id(mqtt_client).publish("hass/script/tokfm", "");
          if (active_page == id(page_play_rmffm))
            id(mqtt_client).publish("hass/script/rmffm", "");
          if (active_page == id(page_play_rmfclassic))
            id(mqtt_client).publish("hass/script/rmfclassic", "");
          if (active_page == id(page_play_rmfmaxx))
            id(mqtt_client).publish("hass/script/rmfmaxx", "");
          if (active_page == id(page_play_podcast))
            id(mqtt_client).publish("hass/script/podcast", "");
          if (active_page == id(page_volume_up))
            id(mqtt_client).publish("hass/script/volume_up", "");
          if (active_page == id(page_volume_down))
            id(mqtt_client).publish("hass/script/volume_down", "");
          if (active_page == id(page_stop_player))
            id(mqtt_client).publish("hass/script/stop_player", "");
          if (active_page == id(page_alarm_off))
            id(mqtt_client).publish("hass/script/alarm_off", "");
          if (active_page == id(page_lights_off))
            id(mqtt_client).publish("hass/script/lights_off", "");
          if (active_page == id(page_sleep)) {
            delay(250);
            id(main_deep_sleep).begin_sleep(true);
          }

display:
  - platform: ssd1306_i2c
    id: main_display
    model: "SSD1306 128x32"
    address: 0x3C
    update_interval: 5s
    pages:
      - id: page_play_rmf24
        lambda: |-
          if (esp_sleep_get_wakeup_cause() == 4) {
            id(main_display).turn_off();
          } else {
            it.print(0, 6, id(main_font), "Play RMF24");
          }
      - id: page_play_radio357
        lambda: it.print(0, 6, id(main_font), "Play Radio 357");
      - id: page_play_antyradio
        lambda: it.print(0, 6, id(main_font), "Play Antyradio");
      - id: page_play_nowyswiat
        lambda: it.print(0, 6, id(main_font), "Play Nowy Swiat");
      - id: page_play_tokfm
        lambda: it.print(0, 6, id(main_font), "Play TOK FM");
      - id: page_play_rmffm
        lambda: it.print(0, 6, id(main_font), "Play RMF FM");
      - id: page_play_rmfclassic
        lambda: it.print(0, 6, id(main_font), "Play RMF Classic");
      - id: page_play_rmfmaxx
        lambda: it.print(0, 6, id(main_font), "Play RMF MAXX");
      - id: page_play_podcast
        lambda: it.print(0, 6, id(main_font), "Play podcast");
      - id: page_volume_up
        lambda: it.print(0, 6, id(main_font), "Volume up");
      - id: page_volume_down
        lambda: it.print(0, 6, id(main_font), "Volume down");
      - id: page_stop_player
        lambda: it.print(0, 6, id(main_font), "Stop player");
      - id: page_alarm_off
        lambda: it.print(0, 6, id(main_font), "Turn alarm off");
      - id: page_lights_off
        lambda: it.print(0, 6, id(main_font), "Turn lights off");
      - id: page_sleep
        lambda: it.print(0, 6, id(main_font), "Go to sleep");
      - id: page_battery
        lambda: |-
          if (id(battery).state) {
            it.printf(0, 6, id(main_font), "Battery %.0f %%", id(battery).state);
          } else {
            it.printf(0, 6, id(main_font), "Battery (wait)");
          }
      - id: page_temperature
        lambda: it.printf(0, 6, id(main_font), "Temp %.2f °C", id(temperature).state);
      #- id: page_pressure
      #  lambda: it.printf(0, 6, id(main_font), "Press %.0f hPa", id(pressure).state);

font:
  - file: "fonts/Lato-Regular.ttf"
    id: main_font
    size: 16

binary_sensor:
  - platform: gpio
    id: click
    internal: true
    pin:
      number: GPIO12
      inverted: true
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
       - script.execute: menu_action

sensor:
  - platform: wifi_signal
    name: "${friendly_name} - WiFi"
    update_interval: 60s

  - platform: adc
    id: battery
    name: "${friendly_name} - Bateria"
    pin: GPIO32
    attenuation: 6db
    update_interval: 250ms
    accuracy_decimals: 0
    unit_of_measurement: '%'
    icon: 'mdi:battery-charging'
    filters:
      - multiply: 3.172
      - throttle_average: 2s
      - calibrate_linear:
        - 3.58 -> 0.0
        - 4.17 -> 100.0
      - lambda: return std::min(std::max(0.0f, x), 100.0f);

  - platform: rotary_encoder
    id: rotary
    internal: true
    pin_a:
      number: GPIO27
      mode: INPUT_PULLUP
    pin_b:
      number: GPIO14
      mode: INPUT_PULLUP
    resolution: 2
    on_anticlockwise:
      - display.page.show_next: main_display
      - component.update: main_display
    on_clockwise:
      - display.page.show_previous: main_display
      - component.update: main_display

  - platform: bmp280
    address: 0x76
    temperature:
      id: "temperature"
      name: "${friendly_name} - Temperatura"
    #pressure:
    #  id: "pressure"
    #  name: "${friendly_name} - Ciśnienie"
    update_interval: 60s
