substitutions:
  static_ip: 10.10.0.109
  friendly_name: "Na zewnątrz"

esphome:
  name: outside
  platform: ESP32
  board: lolin32_lite
  
<<: !include common/base.yaml
<<: !include common/main.yaml

sensor:
  - platform: wifi_signal
    name: "${friendly_name} - WiFi"
    #update_interval: 1s

  - platform: adc
    name: "${friendly_name} - Bateria"
    pin: GPIO32
    attenuation: 6db
    update_interval: 1s
    accuracy_decimals: 2
    filters:
      - multiply: 3.172
