substitutions:
  static_ip: 10.10.0.113
  friendly_name: "Toaleta"

esphome:
  name: toilet

esp32:
  board: esp32dev

<<: !include common/base.yaml

deep_sleep:
  id: deep_sleep_1
  run_duration: 10s
  sleep_duration: 5min

mqtt:
  broker: 10.10.0.103
  discovery: true
  topic_prefix: toilet
  birth_message:
    topic: toilet/availability
    payload: ""
  will_message:
    topic: toilet/availability
    payload: ""
  on_message:
    - topic: toilet/ota_mode
      payload: "ON"
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: toilet/ota_mode
      payload: "OFF"
      then:
        - deep_sleep.enter: deep_sleep_1

sensor:
  - platform: wifi_signal
    name: "${friendly_name} - WiFi"
    update_interval: 5s

  - platform: dht
    model: DHT11
    pin: GPIO19
    temperature:
      id: "temperature"
      name: "${friendly_name} - Temperatura"
    humidity:
      id: "humidity"
      name: "${friendly_name} - Wilgotnosc"
    update_interval: 5s
