wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high
  fast_connect: true

  manual_ip:
    static_ip: "${static_ip}"
    gateway: 10.10.0.10
    subnet: 255.255.255.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8

ota:
  password: !secret ota_password
